### ISSUE TITLE
Is yarn now a requirement?

### ISSUE THREAD

**Issue by TangibleDream** [webdriverio/wdio#2]
A week or so ago,  cloning a repo in my jenkins nightly run, started yelling for yarn to be installed.

`+ BLAH_URL=http://172.17.0.4:3000 /ISOLATED_SELENIUM/run-tests.sh`

`Test Work DIR: /home/jenkins/worker/workspace/BLAH/nightly-selenium`

`> ybr-selenium@1.0.0 test:jenkins /ISOLATED_SELENIUM`

`> wdio wdio.conf.js`

 `                -:...........................-:.`

`                 +                              +`

 `             '' +      '...'        '...'      + ''

 `           ./+/ +    .:://:::'    '::///::'  ' + ++/.`

`           .+oo+ +    /:+ooo+-/    /-+ooo+-/ ./ + +oo+.`

 `          -ooo+ +    /-+ooo+-/    /-+ooo+-/ .: + +ooo.`

   `         -+o+ +    '::///:-'    '::///::'    + +o+-`

`             ``. /.     `````        `````     .: .```

`                  .----------------------------.`

`           '-::::::::::::::::::::::::::::::::::::::::-'`

 `         .+oooo/:------------------------------:/oooo+.`

`      '.--/oooo-                                  :oooo/--.'`

`    .::-'':oooo'                                  .oooo-''-::.`

`  ./-'    -oooo'--.: :.--                         .oooo-    '-/.`

` -/'    '-/oooo////////////////////////////////////oooo/.'    '/-`

`+'   '/+oooooooooooooooooooooooooooooooooooooooooooooooo+:'   .+`

`-/    +o/.:oooooooooooooooooooooooooooooooooooooooooooo:-/o/    +.`

`-/   .o+  -oooosoooososssssooooo------------------:oooo- 'oo'   +.`

`-/   .o+  -oooodooohyyssosshoooo'                 .oooo-  oo.   +.`

`-/   .o+  -oooodooysdooooooyyooo' '.--.''     .:::-oooo-  oo.   +.`

`-/   .o+  -oooodoyyodsoooooyyooo.//-..-:/:.'.//.'./oooo-  oo.   +.`

`-/   .o+  -oooohsyoooyysssysoooo+-'     '-:::.    .oooo-  oo.   +.`

`-/   .o+  -ooooosooooooosooooooo+//////////////////oooo-  oo.   +.`

`-/   .o+  -oooooooooooooooooooooooooooooooooooooooooooo-  oo.   +.`

`-/   .o+  -oooooooooooooooooooooooooooooooooooooooooooo-  oo.   +.`

`-+////o+' -oooo---:///:----://::------------------:oooo- 'oo////+-`

`+ooooooo/'-oooo'':-'''.:'.:.'.+/-    .::::::::::' .oooo-'+ooooooo+`

`oooooooo+'-oooo'-- '/' .:+  -/-'/'   .::::::::::  .oooo-.+oooooooo`

`+-/+://-/ -oooo-':'.o-':.:-''''.:    .///:''''''  -oooo-'/-//:+:-+`

`: :..--:-:.+ooo+/://o+/-.-:////:-....-::::-....--/+ooo+.:.:--.-- /`

`- /./'-:-' .:///+/ooooo/+///////////////+++ooooo/+///:. .-:.'+./ :`

`:-:/.           :'ooooo'/'              .:.ooooo :           ./---`

`                :'ooooo'/'              .:.ooooo :'

`                :'ooooo./'              .:-ooooo :`

 `               :'ooooo./'              .:-ooooo :`

`            '...:-+++++:/.              ./:+++++-:...'`

`           :-.''''''''/../              /.-:''''''''.:-`

`          -/::::::::://:/+             '+/:+::::::::::+.`

`          :oooooooooooo++/              +++oooooooooooo-`

 

 `                          Webdriver.IO`

`              Next-gen browser and mobile automation`

                    test framework for Node.js

`events.js:291`

`      throw er; // Unhandled 'error' event`

 `     ^`

`Error: spawn yarnpkg ENOENT`

`    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)`

`    at onErrorNT (internal/child_process.js:470:16)`

`    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

`Emitted 'error' event on ChildProcess instance at:`

`    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)`

 `   at onErrorNT (internal/child_process.js:470:16)`

`    at processTicksAndRejections (internal/process/task_queues.js:84:21) {`

`  errno: 'ENOENT',`

`  code: 'ENOENT',`

`  syscall: 'spawn yarnpkg',`

`  path: 'yarnpkg',`

`  spawnargs: [ '--version' ]`

`}`

`npm ERR! code ELIFECYCLE`

`npm ERR! errno 1`

`npm ERR! ybr-selenium@1.0.0 test:jenkins: 'wdio wdio.conf.js'`

`npm ERR! Exit status 1`

`npm ERR! `

`npm ERR! Failed at the ybr-selenium@1.0.0 test:jenkins script.`

`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

`npm ERR! A complete log of this run can be found in:`

`npm ERR!     /root/.npm/_logs/2021-09-02T08_06_12_087Z-debug.log`

`script returned exit code 1`

I was able to continue testing after adding Yarn and create a Yarn.lock.     This seems like a really bad Idea.

Please advise.

**Comment by christian-bromann** [comment]
Which environment are you running in? This should normally work out of the box with NPM as well.

**Comment by jdvivasmartin** [comment]
This is also happening to me too. And there's more:

* First, when you run npx wdio or anything similar always tries to go for yarn first (happens mostly in docker but was able to replicate locally).
* Also when it uses yarn, instead of using the wdio.conf.js (or even the run wdio.conf.js) to run the configuration, it creates a folder and tries to initiate a new project withing. If you pass no argument then it creates a config folder, if you pass run wdio.conf.js then it creates a folder called run, and if you pass wdio.conf.js you receive an exception.

**Comment by andreasmarkussen** [comment]
We see it as well, on Windows with NPM v. 14

**Comment by christian-bromann** [comment]
With https://github.com/webdriverio/wdio/commit/91f22a41b90f7104db43fc5b81bcb90d24f774f8 we switched back to NPM as default package manager.
